# Generated by Django 6.0 on 2026-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
